[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "landmark-trajectory-similarity"
version = "1.0.0"
description = "Landmark-based road-network trajectory similarity learning"
requires-python = ">=3.10"
dependencies = [
  "numpy==2.3.5",
  "numba==0.63.1",
  "pandas==2.3.3",
  "pyogrio==0.11.0",
  "scipy==1.16.3",
  "shapely==2.1.2",
  "torch==2.10.0"
]

[tool.setuptools.packages.find]
where = ["src"]
